CREATE DATABASE DEVAPP;
\c devapp
CREATE USER developer WITH PASSWORD '<PASSWORD>';
GRANT ALL PRIVILEGES ON DATABASE DEVAPP TO developer;

CREATE TABLE departments (
    DEPT INT,
    DEPT_NAME VARCHAR(250)
);
GRANT ALL PRIVILEGES ON TABLE departments TO developer;
GRANT ALL PRIVILEGES ON SCHEMA public TO developer;
-- Insert data into departments table
INSERT INTO departments (DEPT, DEPT_NAME) VALUES (1001, 'Sales');
INSERT INTO departments (DEPT, DEPT_NAME) VALUES (1002, 'Marketing');
INSERT INTO departments (DEPT, DEPT_NAME) VALUES (1003, 'HR');
INSERT INTO departments (DEPT, DEPT_NAME) VALUES (1004, 'Admin');
